In [26]:
import matplotlib
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from matplotlib import style, colors
from matplotlib import gridspec

matplotlib.style.use('ggplot')
%matplotlib inline
matplotlib.rcParams['figure.figsize'] = (8, 6)

freeze list 123 patients: HTMCP-03-06-02061, squamous, hiv -, PIK3CA mutated' should exclude this sample

In [27]:
# look at mutation summary file
# f = '/projects/trans_scratch/validations/workspace/szong/Cervical/variant_bwamem/107_patients/106_patients_selected_columns_new.txt'
f = '/projects/trans_scratch/validations/workspace/szong/Cervical/variant_bwamem/124_patients/HIGH_MODERATE_SNV_summary_with_normal_with_AF_filtered_somatic.tsv'
df = pd.read_csv(f, sep='\t')
df.head(2)

/home/szong/anaconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py:2717: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

,gene,chromosome,position,ref_base,alt_base,patient_ID,snp_ID,gmaf,cosmic64_ID,snpeff_details,...,t_RNA_RefC,t_RNA_AltC,t_RNA_AF,RNA_tc,Quality_filter,adj_t_Quality_filter,Somatic_filter,filtered_somatic_num_patients_gene_level,filtered_somatic_num_SNVs_gene_level,filtered_somatic_num_patients_SNV_level
0,WASH7P,1,17365,C,G,HTMCP-03-06-02149_malignant,novel_snp,gmaf_unknown,not_in_cosmic64,SPLICE_SITE_ACCEPTOR(HIGH|||||WASH7P|unprocess...,...,15,0,0.00,50.0,True,True,True,1,1,1
1,SAMD11,1,865615,C,A,HTMCP-03-06-02007_malignant,novel_snp,gmaf_unknown,not_in_cosmic64,NON_SYNONYMOUS_CODING(MODERATE|MISSENSE|ttC/tt...,...,15,9,0.38,50.0,True,True,True,2,2,1

In [28]:
df.describe()

,position,n_DNA_cov_valid_bases,n_DNA_RefC,n_DNA_AltC,n_DNA_AF,t_DNA_cov_valid_bases,t_DNA_RefC,t_DNA_AltC,t_DNA_AF,DNA_tc,t_RNA_cov_valid_bases,t_RNA_RefC,t_RNA_AltC,t_RNA_AF,RNA_tc,filtered_somatic_num_patients_gene_level,filtered_somatic_num_SNVs_gene_level,filtered_somatic_num_patients_SNV_level
count,4.976100e+04,49761.000000,49761.000000,49761.000000,49761.000000,49761.000000,49761.000000,49761.000000,49761.000000,49761.000000,49761.000000,49761.000000,49761.000000,49761.000000,49761.000000,49761.000000,49761.000000,49761.000000
mean,7.882258e+07,59.935009,59.657121,0.134141,0.002891,100.490565,75.752618,24.475453,0.239773,64.000522,185.667410,132.904001,52.183919,0.197778,64.000522,6.207311,12.426117,1.091558
std,5.858612e+07,378.525318,376.951428,1.033984,0.013624,372.098287,286.354834,160.299187,0.118326,14.198556,644.794081,499.051918,242.623155,0.242875,14.198556,12.037620,43.606299,0.731344
min,3.395000e+03,1.000000,1.000000,0.000000,0.000000,6.000000,0.000000,0.000000,0.000000,20.000000,0.000000,0.000000,0.000000,0.000000,20.000000,1.000000,1.000000,1.000000
25%,3.248979e+07,32.000000,32.000000,0.000000,0.000000,65.000000,47.000000,11.000000,0.150000,50.000000,1.000000,0.000000,0.000000,0.000000,50.000000,2.000000,3.000000,1.000000
50%,6.357964e+07,40.000000,40.000000,0.000000,0.000000,80.000000,60.000000,18.000000,0.240000,65.000000,21.000000,14.000000,2.000000,0.080000,65.000000,3.000000,5.000000,1.000000
75%,1.184795e+08,48.000000,48.000000,0.000000,0.000000,95.000000,73.000000,25.000000,0.320000,70.000000,127.000000,87.000000,28.000000,0.370000,70.000000,6.000000,8.000000,1.000000
max,2.491515e+08,8087.000000,8078.000000,80.000000,0.550000,8069.000000,7883.000000,7338.000000,0.980000,90.000000,8120.000000,8046.000000,7720.000000,1.000000,90.000000,106.000000,408.000000,22.000000

In [29]:
df[['n_DNA_cov_valid_bases','t_DNA_cov_valid_bases', 't_RNA_cov_valid_bases','n_DNA_AF','t_DNA_AF', 't_RNA_AF', 'in_strelka']].head()

,n_DNA_cov_valid_bases,t_DNA_cov_valid_bases,t_RNA_cov_valid_bases,n_DNA_AF,t_DNA_AF,t_RNA_AF,in_strelka
0,94,274,15,0.05,0.05,0.00,in_strelka
1,16,32,24,0.00,0.41,0.38,not_in_strelka
2,29,45,1,0.00,0.29,1.00,in_strelka
3,28,53,3,0.00,0.21,0.33,in_strelka
4,43,58,28,0.00,0.09,0.00,in_strelka

In [30]:
ndf = pd.DataFrame(columns = df.columns)
for index, row in df.iterrows():
    n_DNA_cov = row['n_DNA_cov_valid_bases']
    n_DNA_AF = row['n_DNA_AF']
    t_DNA_cov = row['t_DNA_cov_valid_bases']
    t_DNA_AF = row['t_DNA_AF']
    t_RAN_cov = row['t_RNA_cov_valid_bases']
    t_RNA_AF = row ['t_RNA_AF']
    in_strelka = row['in_strelka']
#     print(row)
#     if in_strelka == 'in_strelka':   
#         ndf.loc[index] = row
   
    if float(n_DNA_cov) >= 10 and n_DNA_AF < 0.05:
        if t_DNA_cov >= 10 and t_DNA_AF >= 0.1:
            ndf.loc[index] = row
        elif t_RAN_cov >= 10 and t_RNA_AF >= 0.1:
            ndf.loc[index] = row

In [31]:
ndf.shape

(43370, 40)

In [32]:
ndf.columns

Index(['gene', 'chromosome', 'position', 'ref_base', 'alt_base', 'patient_ID',
       'snp_ID', 'gmaf', 'cosmic64_ID', 'snpeff_details',
       'in_DNA_single_mpileup', 'in_paired_mpileup', 'in_mutseq', 'in_strelka',
       'in_RNA_single_mpileup', 'n_DNA_cov_valid_bases', 'n_DNA_RefC',
       'n_DNA_AltC', 'n_DNA_AF', 't_DNA_cov_valid_bases', 't_DNA_RefC',
       't_DNA_AltC', 't_DNA_AF', 'adj_t_DNA_cov_valid_bases', 'adj_t_DNA_RefC',
       'adj_t_DNA_AltC', 'adj_t_DNA_AF', 'DNA_tc', 'DNA_fisher_pvalue',
       't_RNA_cov_valid_bases', 't_RNA_RefC', 't_RNA_AltC', 't_RNA_AF',
       'RNA_tc', 'Quality_filter', 'adj_t_Quality_filter', 'Somatic_filter',
       'filtered_somatic_num_patients_gene_level',
       'filtered_somatic_num_SNVs_gene_level',
       'filtered_somatic_num_patients_SNV_level'],
      dtype='object')

In [33]:
odf = ndf.groupby('gene')['patient_ID'].nunique().sort_values(ascending=False).to_frame()

In [34]:
odf = odf.rename(columns={'patient_ID':'occurrence_at_gene_level'})
odf.head(2)

      occurrence_at_gene_level
gene
MUC4                        83
TTN                         52

In [35]:
pdf = pd.merge(ndf, odf,left_on='gene', right_index=True, how='left')
pdf.head(2)

,gene,chromosome,position,ref_base,alt_base,patient_ID,snp_ID,gmaf,cosmic64_ID,snpeff_details,...,t_RNA_AltC,t_RNA_AF,RNA_tc,Quality_filter,adj_t_Quality_filter,Somatic_filter,filtered_somatic_num_patients_gene_level,filtered_somatic_num_SNVs_gene_level,filtered_somatic_num_patients_SNV_level,occurrence_at_gene_level
1,SAMD11,1,865615,C,A,HTMCP-03-06-02007_malignant,novel_snp,gmaf_unknown,not_in_cosmic64,NON_SYNONYMOUS_CODING(MODERATE|MISSENSE|ttC/tt...,...,9,0.38,50.0,True,True,True,2,2,1,2
2,SAMD11,1,878183,C,T,HTMCP-03-06-02214_malignant,novel_snp,gmaf_unknown,not_in_cosmic64,NON_SYNONYMOUS_CODING(MODERATE|MISSENSE|Ccc/Tc...,...,1,1.00,90.0,True,True,True,2,2,1,2

In [25]:
of = '/projects/trans_scratch/validations/workspace/szong/Cervical/variant_bwamem/124_patients/124_patients_selected_columns_new_filtered.txt'
# pdf.to_csv(of, sep='\t', index=False)