In [53]:
import matplotlib
import csv
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from matplotlib import style, colors
from matplotlib import gridspec

matplotlib.style.use('ggplot')
%matplotlib inline
matplotlib.rcParams['figure.figsize'] = (8, 6)

freeze list 123 patients: HTMCP-03-06-02061, squamous, hiv -, PIK3CA mutated' should exclude this sample

In [27]:
# look at mutation summary file
# f = '/projects/trans_scratch/validations/workspace/szong/Cervical/variant_bwamem/107_patients/106_patients_selected_columns_new.txt'
f = '/projects/trans_scratch/validations/workspace/szong/Cervical/variant_bwamem/124_patients/HIGH_MODERATE_SNV_summary_with_normal_with_AF_filtered_somatic.tsv'
df = pd.read_csv(f, sep='\t')
df.head(2)

/home/szong/anaconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py:2717: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

,gene,chromosome,position,ref_base,alt_base,patient_ID,snp_ID,gmaf,cosmic64_ID,snpeff_details,...,t_RNA_RefC,t_RNA_AltC,t_RNA_AF,RNA_tc,Quality_filter,adj_t_Quality_filter,Somatic_filter,filtered_somatic_num_patients_gene_level,filtered_somatic_num_SNVs_gene_level,filtered_somatic_num_patients_SNV_level
0,WASH7P,1,17365,C,G,HTMCP-03-06-02149_malignant,novel_snp,gmaf_unknown,not_in_cosmic64,SPLICE_SITE_ACCEPTOR(HIGH|||||WASH7P|unprocess...,...,15,0,0.00,50.0,True,True,True,1,1,1
1,SAMD11,1,865615,C,A,HTMCP-03-06-02007_malignant,novel_snp,gmaf_unknown,not_in_cosmic64,NON_SYNONYMOUS_CODING(MODERATE|MISSENSE|ttC/tt...,...,15,9,0.38,50.0,True,True,True,2,2,1

In [28]:
df.describe()

,position,n_DNA_cov_valid_bases,n_DNA_RefC,n_DNA_AltC,n_DNA_AF,t_DNA_cov_valid_bases,t_DNA_RefC,t_DNA_AltC,t_DNA_AF,DNA_tc,t_RNA_cov_valid_bases,t_RNA_RefC,t_RNA_AltC,t_RNA_AF,RNA_tc,filtered_somatic_num_patients_gene_level,filtered_somatic_num_SNVs_gene_level,filtered_somatic_num_patients_SNV_level
count,4.976100e+04,49761.000000,49761.000000,49761.000000,49761.000000,49761.000000,49761.000000,49761.000000,49761.000000,49761.000000,49761.000000,49761.000000,49761.000000,49761.000000,49761.000000,49761.000000,49761.000000,49761.000000
mean,7.882258e+07,59.935009,59.657121,0.134141,0.002891,100.490565,75.752618,24.475453,0.239773,64.000522,185.667410,132.904001,52.183919,0.197778,64.000522,6.207311,12.426117,1.091558
std,5.858612e+07,378.525318,376.951428,1.033984,0.013624,372.098287,286.354834,160.299187,0.118326,14.198556,644.794081,499.051918,242.623155,0.242875,14.198556,12.037620,43.606299,0.731344
min,3.395000e+03,1.000000,1.000000,0.000000,0.000000,6.000000,0.000000,0.000000,0.000000,20.000000,0.000000,0.000000,0.000000,0.000000,20.000000,1.000000,1.000000,1.000000
25%,3.248979e+07,32.000000,32.000000,0.000000,0.000000,65.000000,47.000000,11.000000,0.150000,50.000000,1.000000,0.000000,0.000000,0.000000,50.000000,2.000000,3.000000,1.000000
50%,6.357964e+07,40.000000,40.000000,0.000000,0.000000,80.000000,60.000000,18.000000,0.240000,65.000000,21.000000,14.000000,2.000000,0.080000,65.000000,3.000000,5.000000,1.000000
75%,1.184795e+08,48.000000,48.000000,0.000000,0.000000,95.000000,73.000000,25.000000,0.320000,70.000000,127.000000,87.000000,28.000000,0.370000,70.000000,6.000000,8.000000,1.000000
max,2.491515e+08,8087.000000,8078.000000,80.000000,0.550000,8069.000000,7883.000000,7338.000000,0.980000,90.000000,8120.000000,8046.000000,7720.000000,1.000000,90.000000,106.000000,408.000000,22.000000

In [29]:
df[['n_DNA_cov_valid_bases','t_DNA_cov_valid_bases', 't_RNA_cov_valid_bases','n_DNA_AF','t_DNA_AF', 't_RNA_AF', 'in_strelka']].head()

,n_DNA_cov_valid_bases,t_DNA_cov_valid_bases,t_RNA_cov_valid_bases,n_DNA_AF,t_DNA_AF,t_RNA_AF,in_strelka
0,94,274,15,0.05,0.05,0.00,in_strelka
1,16,32,24,0.00,0.41,0.38,not_in_strelka
2,29,45,1,0.00,0.29,1.00,in_strelka
3,28,53,3,0.00,0.21,0.33,in_strelka
4,43,58,28,0.00,0.09,0.00,in_strelka

In [30]:
ndf = pd.DataFrame(columns = df.columns)
for index, row in df.iterrows():
    n_DNA_cov = row['n_DNA_cov_valid_bases']
    n_DNA_AF = row['n_DNA_AF']
    t_DNA_cov = row['t_DNA_cov_valid_bases']
    t_DNA_AF = row['t_DNA_AF']
    t_RAN_cov = row['t_RNA_cov_valid_bases']
    t_RNA_AF = row ['t_RNA_AF']
    in_strelka = row['in_strelka']
#     print(row)
#     if in_strelka == 'in_strelka':   
#         ndf.loc[index] = row
   
    if float(n_DNA_cov) >= 10 and n_DNA_AF < 0.05:
        if t_DNA_cov >= 10 and t_DNA_AF >= 0.1:
            ndf.loc[index] = row
        elif t_RAN_cov >= 10 and t_RNA_AF >= 0.1:
            ndf.loc[index] = row

In [31]:
ndf.shape

(43370, 40)

In [32]:
ndf.columns

Index(['gene', 'chromosome', 'position', 'ref_base', 'alt_base', 'patient_ID',
       'snp_ID', 'gmaf', 'cosmic64_ID', 'snpeff_details',
       'in_DNA_single_mpileup', 'in_paired_mpileup', 'in_mutseq', 'in_strelka',
       'in_RNA_single_mpileup', 'n_DNA_cov_valid_bases', 'n_DNA_RefC',
       'n_DNA_AltC', 'n_DNA_AF', 't_DNA_cov_valid_bases', 't_DNA_RefC',
       't_DNA_AltC', 't_DNA_AF', 'adj_t_DNA_cov_valid_bases', 'adj_t_DNA_RefC',
       'adj_t_DNA_AltC', 'adj_t_DNA_AF', 'DNA_tc', 'DNA_fisher_pvalue',
       't_RNA_cov_valid_bases', 't_RNA_RefC', 't_RNA_AltC', 't_RNA_AF',
       'RNA_tc', 'Quality_filter', 'adj_t_Quality_filter', 'Somatic_filter',
       'filtered_somatic_num_patients_gene_level',
       'filtered_somatic_num_SNVs_gene_level',
       'filtered_somatic_num_patients_SNV_level'],
      dtype='object')

In [33]:
odf = ndf.groupby('gene')['patient_ID'].nunique().sort_values(ascending=False).to_frame()

In [34]:
odf = odf.rename(columns={'patient_ID':'occurrence_at_gene_level'})
odf.head(2)

      occurrence_at_gene_level
gene
MUC4                        83
TTN                         52

In [35]:
pdf = pd.merge(ndf, odf,left_on='gene', right_index=True, how='left')
pdf.head(2)

,gene,chromosome,position,ref_base,alt_base,patient_ID,snp_ID,gmaf,cosmic64_ID,snpeff_details,...,t_RNA_AltC,t_RNA_AF,RNA_tc,Quality_filter,adj_t_Quality_filter,Somatic_filter,filtered_somatic_num_patients_gene_level,filtered_somatic_num_SNVs_gene_level,filtered_somatic_num_patients_SNV_level,occurrence_at_gene_level
1,SAMD11,1,865615,C,A,HTMCP-03-06-02007_malignant,novel_snp,gmaf_unknown,not_in_cosmic64,NON_SYNONYMOUS_CODING(MODERATE|MISSENSE|ttC/tt...,...,9,0.38,50.0,True,True,True,2,2,1,2
2,SAMD11,1,878183,C,T,HTMCP-03-06-02214_malignant,novel_snp,gmaf_unknown,not_in_cosmic64,NON_SYNONYMOUS_CODING(MODERATE|MISSENSE|Ccc/Tc...,...,1,1.00,90.0,True,True,True,2,2,1,2

In [4]:
of = '/projects/trans_scratch/validations/workspace/szong/Cervical/variant_bwamem/124_patients/124_patients_selected_columns_new_filtered.txt'
# pdf.to_csv(of, sep='\t', index=False)

In [6]:
# figure out validation gene set: recurrent in >= 3 patients + epigenetic genes + non_coding hotspots
df = pd.read_csv(of, sep='\t')
df.head(2)

/home/szong/anaconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py:2717: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

,gene,chromosome,position,ref_base,alt_base,patient_ID,snp_ID,gmaf,cosmic64_ID,snpeff_details,...,t_RNA_AltC,t_RNA_AF,RNA_tc,Quality_filter,adj_t_Quality_filter,Somatic_filter,filtered_somatic_num_patients_gene_level,filtered_somatic_num_SNVs_gene_level,filtered_somatic_num_patients_SNV_level,occurrence_at_gene_level
0,SAMD11,1,865615,C,A,HTMCP-03-06-02007,novel_snp,gmaf_unknown,not_in_cosmic64,NON_SYNONYMOUS_CODING(MODERATE|MISSENSE|ttC/tt...,...,9,0.38,50.0,True,True,True,2,2,1,2
1,SAMD11,1,878183,C,T,HTMCP-03-06-02214,novel_snp,gmaf_unknown,not_in_cosmic64,NON_SYNONYMOUS_CODING(MODERATE|MISSENSE|Ccc/Tc...,...,1,1.00,90.0,True,True,True,2,2,1,2

In [7]:
df.shape

(43370, 41)

In [11]:
dfa = df[['gene', 'patient_ID']].drop_duplicates()
dfa.shape

(33606, 2)

In [16]:
dfb = dfa.groupby('gene').count().sort_values('patient_ID', ascending=False)

In [17]:
dfb.head(2)

      patient_ID
gene
MUC4          83
TTN           52

In [21]:
dfc = dfb[dfb.patient_ID >=3]

In [25]:
dfc.shape

(4622, 1)

In [24]:
of2 = '/projects/trans_scratch/validations/workspace/szong/Cervical/variant_bwamem/124_patients/genes_mutated_in_3_or_mroe_patients.txt'
dfc.to_csv(of2)

In [30]:
f = '/projects/trans_scratch/validations/workspace/szong/Cervical/tcga_variants/tcga_mutations.tmp'
df = pd.read_csv(f, sep='\t', header=None)
df.head()

          0                             1
0  A1BG-AS1  TCGA-EK-A3GM-01A-11D-A20U-09
1      A1BG  TCGA-BI-A0VS-01A-11D-A10S-08
2      A1CF  TCGA-EK-A3GJ-01A-21D-A20U-09
3      A1CF  TCGA-Q1-A6DT-01A-11D-A32I-09
4     A2ML1  TCGA-EK-A2RB-01A-11D-A18J-09

In [37]:
dfb = df.groupby(0).count().sort_values(1, ascending=False)
dfb.head()

         1
0
TTN     80
PIK3CA  53
MUC4    42
MUC16   33
SYNE1   31

In [49]:
dfc = dfb[dfb[1] >=3].index.tolist()

In [44]:
dfc

['TTN',
 'PIK3CA',
 'MUC4',
 'MUC16',
 'SYNE1',
 'KMT2C',
 'KMT2D',
 'GPR98',
 'DST',
 'RYR2',
 'SYNE2',
 'OBSCN',
 'MUC5B',
 'XIST',
 'EP300',
 'DMD',
 'ENSG00000259660',
 'FLG',
 'HELZ2',
 'FBXW7',
 'MUC12',
 'USH2A',
 'NEB',
 'CROCCP2',
 'HMCN1',
 'PLEC',
 'FCGBP',
 'AHNAK2',
 'ZFHX3',
 'ABCA12',
 'MDN1',
 'RYR1',
 'LRP2',
 'NAV3',
 'CSMD1',
 'CREBBP',
 'DNAH3',
 'APOB',
 'MUC17',
 'HLA-A',
 'MYO15A',
 'PDE4DIP',
 'PCLO',
 'ARID1A',
 'RNF213',
 'VCAN',
 'DNAH6',
 'DCHS1',
 'PTEN',
 'MYH9',
 'PKD1',
 'DYNC1H1',
 'LOC440993',
 'MACF1',
 'SPTAN1',
 'FSIP2',
 'UBR4',
 'WIZ',
 'CSMD3',
 'XIRP2',
 'FAT4',
 'TENM4',
 'DNAH10',
 'DNAH2',
 'GOLGB1',
 'LRP1B',
 'HRNR',
 'DNAH5',
 'FLNC',
 'MGAM',
 'BSN',
 'ATRX',
 'TRRAP',
 'PRKDC',
 'SMG1',
 'MALAT1',
 'ZFHX4',
 'DNAH11',
 'DCHS2',
 'PKHD1L1',
 'RYR3',
 'MYH13',
 'TENM1',
 'CMYA5',
 'ABCA13',
 'NFE2L2',
 'FAT1',
 'FAT2',
 'FAT3',
 'TSC2',
 'NBEAL1',
 'BAI3',
 'WDFY4',
 'VPS13B',
 'VPS13A',
 'HERC2',
 'PCDH15',
 'GPR179',
 'ZDHHC11B',
 'IGFN1',
 'TENM2',
 'DNAH1',
 'CHD6',
 'CHD7',
 'EYS',
 'AKAP13',
 'PKHD1',
 'AHCTF1',
 'EP400',
 'PTPRT',
 'MYT1L',
 'SPEN',
 'HUWE1',
 'MXRA5',
 'CUBN',
 'SRCAP',
 'HIVEP1',
 'MTOR',
 'DNAH9',
 'HSPG2',
 'MAP2',
 'MYH2',
 'MYH15',
 'RGPD4',
 'DLC1',
 'FRAS1',
 'CHD4',
 'DNAH8',
 'POLQ',
 'FREM3',
 'ASPM',
 'ANKHD1',
 'ANK3',
 'ANK2',
 'PCNT',
 'ZNF536',
 'PTPRD',
 'NRXN1',
 'MUC2',
 'SSPO',
 'ADAMTS20',
 'DSP',
 'NOTCH1',
 'ZAN',
 'MYO7B',
 'CACNA1B',
 'SI',
 'UHRF1BP1',
 'CACNA1C',
 'BRWD3',
 'NHS',
 'ZNF814',
 'DYNC2H1',
 'GTF3C1',
 'NBEA',
 'FLNA',
 'PLCB1',
 'ALMS1',
 'KIF26B',
 'SYTL2',
 'KIF1A',
 'DCC',
 'TNXB',
 'TNIK',
 'ENSG00000238261',
 'HECTD4',
 'CDH23',
 'AKNA',
 'HIVEP2',
 'MED1',
 'HLA-B',
 'HFM1',
 'PTPRF',
 'NSD1',
 'ERBB2',
 'KNTC1',
 'KRAS',
 'BPTF',
 'DSCAML1',
 'MGA',
 'ERBB3',
 'DNAH7',
 'KIAA0947',
 'RPGR',
 'TRPM1',
 'THSD7B',
 'HYDIN',
 'ATM',
 'COL6A3',
 'MAP1B',
 'MAP1A',
 'ARMCX4',
 'SMARCA4',
 'MYH3',
 'SPTBN5',
 'PLIN4',
 'MAGEC3',
 'SPATA31D1',
 'CECR2',
 'COL11A1',
 'TEX15',
 'PLXNA3',
 'CELSR2',
 'DMXL2',
 'GPR112',
 'DNAH17',
 'PLCE1',
 'INTS1',
 'ENSG00000232274',
 'C4orf21',
 'FBN2',
 'ARHGAP6',
 'BOD1L1',
 'PDZD2',
 'LOC100996870',
 'LAMA2',
 'ITPR1',
 'CHD3',
 'COL24A1',
 'ZNF750',
 'ZFYVE26',
 'PSD',
 'CROCC',
 'TPR',
 'KDM2A',
 'NIPBL',
 'TP73',
 'AFF3',
 'NPAP1',
 'TP53BP1',
 'TP53',
 'AR',
 'SPAG17',
 'USP43',
 'TCHH',
 'THSD7A',
 'PTPRM',
 'PREX1',
 'NBEAL2',
 'RELN',
 'CPSF1',
 'NBPF1',
 'NBPF10',
 'TDRD6',
 'PTPRC',
 'DIDO1',
 'BAI2',
 'FMN2',
 'C1orf173',
 'TTC3',
 'PARP14',
 'F8',
 'COL12A1',
 'ABL1',
 'SPTA1',
 'ZNF99',
 'NOTCH3',
 'LRP5',
 'WNK1',
 'PPL',
 'KIAA2026',
 'MAST4',
 'MYBPC2',
 'MYCBP2',
 'MYH10',
 'DOPEY2',
 'IQGAP1',
 'COL19A1',
 'MYH7',
 'CACNA1E',
 'CACNA1H',
 'MYH8',
 'MKI67',
 'MAP3K5',
 'CNTNAP2',
 'LATS1',
 'ZEB2',
 'ADAMTS12',
 'PLCH1',
 'TMEM132C',
 'KIAA0754',
 'ADAMTS16',
 'PCDHGA2',
 'MED12',
 'VPS13C',
 'GOLGA4',
 'ADCY8',
 'ADAMTSL1',
 'BIRC6',
 'ZNF521',
 'TRIOBP',
 'TRIM9',
 'CSMD2',
 'MYH1',
 'KIDINS220',
 'NF1',
 'AK9',
 'LRRC37A3',
 'LYST',
 'DOPEY1',
 'NYNRIN',
 'MCF2L',
 'UBR5',
 'C12orf55',
 'YTHDC2',
 'LRRC41',
 'CADPS',
 'FAM208B',
 'SNHG14',
 'YLPM1',
 'RB1',
 'TIE1',
 'OBSL1',
 'ZNF236',
 'ASTN1',
 'TEP1',
 'SVIL',
 'FRY',
 'PTPN13',
 'AHNAK',
 'LRP1',
 'WDR81',
 'FREM2',
 'HSD17B4',
 'DMBT1',
 'LRRK2',
 'RIMS1',
 'COL7A1',
 'KIF1B',
 'PRDM9',
 'VWA5B1',
 'ATP10A',
 'SVEP1',
 'C2CD3',
 'SRGAP1',
 'TTLL10-AS1',
 'EGFR',
 'SRRM2',
 'MPDZ',
 'ARHGAP35',
 'BCOR',
 'POLR2A',
 'TMC2',
 'MAPK1',
 'CENPF',
 'TRPM6',
 'UACA',
 'TCF20',
 'DOCK11',
 'GRIA3',
 'SRRT',
 'ATG2B',
 'DSPP',
 'SND1',
 'RIMS2',
 'TICRR',
 'EML6',
 'POLR1A',
 'GPRASP1',
 'ADCY10',
 'ROBO1',
 'SCN8A',
 'CCDC180',
 'KIAA1109',
 'MED12L',
 'PLXNC1',
 'CIC',
 'STXBP4',
 'TAF1L',
 'OTOG',
 'ZNF638',
 'KIAA1244',
 'HERC1',
 'SCN4A',
 'NAA15',
 'USP34',
 'CASP8',
 'BRWD1',
 'KIAA0556',
 'PRUNE2',
 'HECW1',
 'UNC80',
 'CCDC108',
 'ARFGEF2',
 'KMT2A',
 'MAGEE1',
 'SIPA1L2',
 'RTTN',
 'BAZ2B',
 'PHKA2',
 'UTRN',
 'ADCY9',
 'CNTRL',
 'ZNF318',
 'ZC3H11A',
 'ARPP21',
 'TNRC18',
 'KIAA1009',
 'VPS13D',
 'DAP3',
 'KDM5A',
 'GON4L',
 'VWF',
 'USP9X',
 'APC',
 'FHAD1',
 'RPTOR',
 'FOLH1',
 'MROH2B',
 'UTP20',
 'CLTCL1',
 'CUX1',
 'USPL1',
 'ATP2B2',
 'CIZ1',
 'LIG4',
 'SPTBN2',
 'ALPK2',
 'MAST1',
 'CNTNAP5',
 'PI4KA',
 'LARP1',
 'PARD3',
 'TET1',
 'FLG2',
 'EPHA2',
 'TENM3',
 'ACAN',
 'SPG11',
 'WDR65',
 'FLNB',
 'BDP1',
 'RPGRIP1',
 'RRBP1',
 'EHMT1',
 'SIPA1L1',
 'DNAH14',
 'UNC79',
 'SPEG',
 'FAM47C',
 'RP1',
 'WBSCR17',
 'WDFY3',
 'WNK3',
 'ATP8B2',
 'CHD8',
 'BAIAP3',
 'WDR87',
 'IGSF9B',
 'IGSF9',
 'PLEKHA1',
 'PHC2',
 'BCORL1',
 'MAST3',
 'ANKRD12',
 'KIAA0100',
 'IGSF10',
 'KTN1',
 'INTS3',
 'SEC31A',
 'CEP350',
 'TDRD1',
 'PRDM2',
 'EPHA5',
 'ABCA2',
 'NBAS',
 'NAV2',
 'PTPRK',
 'KANK1',
 'COL2A1',
 'KALRN',
 'PRRC2B',
 'PRRC2A',
 'ARMC4',
 'TNS1',
 'HEATR1',
 'TARBP1',
 'NRAP',
 'MADD',
 'RUNX1T1',
 'ABCC3',
 'TPO',
 'SCN7A',
 'FYCO1',
 'ZBTB38',
 'LPHN3',
 'PCSK5',
 'ZBBX',
 'FAM171A1',
 'LEPR',
 'CDK5RAP2',
 'CAMSAP1',
 'LAMA5',
 'COL4A2',
 'MAP3K15',
 'PCDH17',
 'COL6A5',
 'ZFHX2',
 'MAGEC1',
 'PCDHA11',
 'GRIN2A',
 'ARHGEF11',
 'GRIP2',
 'ENSG00000218819',
 'ARHGEF12',
 'GSN',
 'SLITRK1',
 'COL4A5',
 'SLIT3',
 'GTF2IRD2P1',
 'PLXNA2',
 'PLXNA4',
 'DSCAM',
 'ABCA4',
 'NCOR2',
 'TANC2',
 'CDH10',
 'CDH11',
 'CCDC77',
 'PCDH19',
 'SCN2A',
 'SACS',
 'PCDHA2',
 'ASH1L',
 'KLHL4',
 'DLG5',
 'NUP188',
 'RBMXL3',
 'PEAK1',
 'ZNF91',
 'DOCK1',
 'ITGB4',
 'TRIP11',
 'TRIP12',
 'KIF7',
 'CSPG4',
 'NLGN4X',
 'SMG6',
 'TSPEAR',
 'MYH6',
 'FRMPD2',
 'DCAF8L2',
 'XRRA1',
 'TG',
 'DOCK9',
 'NLRP1',
 'SCRIB',
 'NOTCH4',
 'LRPPRC',
 'HMGB1P5',
 'MTUS2',
 'SEC16A',
 'COL15A1',
 'TTBK1',
 'HNRNPR',
 'TTF2',
 'ENSG00000225411',
 'SMCHD1',
 'FSTL5',
 'ABCD1',
 'CAD',
 'MAP3K4',
 'TTC40',
 'TTC28',
 'CACNB4',
 'ABCD3',
 'LRRC16A',
 'NOTCH2',
 'DENND4C',
 'ITGA4',
 'LAMA1',
 'ARHGAP36',
 'INPP5D',
 'ATP10B',
 'ARHGEF4',
 'ZNF8',
 'EFCAB6',
 'RICTOR',
 'FER1L6',
 'ARHGEF9',
 'ATP2B3',
 'SNAP91',
 'ARID2',
 'RIF1',
 'BAZ1B',
 'ARHGEF2',
 'YTHDF3',
 'SMAD4',
 'ARID4A',
 'ZDBF2',
 'MAP3K19',
 'ZNF804B',
 'WDR90',
 'MAP3K14',
 'SMC4',
 'WDR7',
 'ITSN2',
 'FBN1',
 'MAPKAPK2',
 'RLTPR',
 'PRR12',
 'MBD6',
 'WDR6',
 'FCRL1',
 'MAP4',
 'ATAD2',
 'JAKMIP3',
 'CHD5',
 'DENND2C',
 'JARID2',
 'IQGAP2',
 'DGKK',
 'PEX5L',
 'PCDH11X',
 'MAP7D3',
 'PRG4',
 'SIPA1L3',
 'PARD3B',
 'NPAS4',
 'SMG8',
 'ADAM21P1',
 'SDK2',
 'CAPRIN1',
 'ENPP3',
 'COL22A1',
 'HIF1A',
 'MYO5A',
 'CAMTA1',
 'MYO9A',
 'SCN9A',
 'SGSM1',
 'NLRP11',
 'ENSG00000161103',
 'CARD11',
 'MYRIP',
 'CASKIN2',
 'STARD9',
 'TP63',
 'CASZ1',
 'ENPP2',
 'THADA',
 'HIST1H1B',
 'MYO16',
 'TRPM2',
 'NLRC3',
 'TRPC3',
 'C9orf3',
 'TRIO',
 'LIN9',
 'MYH4',
 'RALGAPA1',
 'CACNA1F',
 'CACNA1I',
 'MYH7B',
 'CACNA2D3',
 'ST5',
 'MYO10',
 'NLGN3',
 'CDK13',
 'SCN5A',
 'ABCC10',
 'PLXNB2',
 'TIAM1',
 'SETDB1',
 'CCPG1',
 'SBNO1',
 'COL5A1',
 'TMEM132D',
 'TMEM131',
 'GRM8',
 'TIMELESS',
 'TMC6',
 'GRIK5',
 'NWD1',
 'SUSD4',
 'ABCA7',
 'COL6A6',
 'PLXNA1',
 'NCOR1',
 'TNS3',
 'SETX',
 'COL27A1',
 'CDHR2',
 'CRB1',
 'CCDC141',
 'PER3',
 'SFSWAP',
 'CCDC168',
 'EPRS',
 'CCDC37',
 'EPPK1',
 'NCAM1',
 'NCAM2',
 'SEZ6L',
 'PML',
 'GVINP1',
 'NLRC5',
 'PDZD7',
 'IMPG2',
 'IGF2BP1',
 'USP51',
 'USP48',
 'LAS1L',
 'USP26',
 'OTOA',
 'USP11',
 'UROC1',
 'ESPL1',
 'MUC20',
 'CEP192',
 'CEP170',
 'ROR2',
 'RORC',
 'ROS1',
 'UNC13A',
 'MIA3',
 'USP8',
 'ELF3',
 'CNTNAP1',
 'MED23',
 'BCLAF1',
 'PRDM16',
 'TJP1',
 'BCR',
 'VPS52',
 'MDC1',
 'MDGA2',
 'BEND3',
 'ACIN1',
 'BEST3',
 'IL4R',
 'SORBS1',
 'MED13',
 'SORL1',
 'SDHAP1',
 'MICAL3',
 'RP1L1',
 'FAM135B',
 'MORC3',
 'TULP4',
 'SPTBN1',
 'C1orf112',
 'TUBGCP6',
 'SPTBN4',
 'AATK',
 'MPP5',
 'CELSR1',
 'C1orf222',
 'CUL1',
 'TTLL5',
 'CTNND2',
 'CTNNA3',
 'C3',
 'SRPK2',
 'MOV10L1',
 'CELSR3',
 'IDS',
 'TYK2',
 'PZP',
 'DZIP1',
 'SPHKAP',
 'FLT1',
 'EPHA4',
 'FLT4',
 'ACACB',
 'HTT',
 'PPP1R12A',
 'UBE3C',
 'ACACA',
 'UBAP2L',
 'ARHGAP31',
 'CENPE',
 'FNDC1',
 'FMR1',
 'TJP2',
 'DNAJC14',
 'GLIS3',
 'AOX2P',
 'ADCY5',
 'LRIG2',
 'LTBP4',
 'RBM10',
 'DMKN',
 'KMT2B',
 'LOC642633',
 'ENTPD4',
 'ADAM15',
 'RAD54L2',
 'PTPRS',
 'DNAJC13',
 'SLIT2',
 'SEMA4B',
 'PTPRB',
 'RBFOX1',
 'SLC27A5',
 'PDE4B',
 'PCDHA7',
 'DOT1L',
 'L1CAM',
 'PTGFRN',
 'PCDHB6',
 'ZNF646',
 'ALS2CL',
 'ANKFN1',
 'CLCNKA',
 'ALPK3',
 'KIF13B',
 'SLC34A2',
 'KRT1',
 'KIF20B',
 'KNDC1',
 'PCNXL2',
 'PDE1C',
 'KIAA1239',
 'DPCR1',
 'PTPRN2',
 'PDE3A',
 'CLCC1',
 'ANKRD26',
 'RGAG1',
 'LRSAM1',
 'GNPTAB',
 'EPB41L3',
 'KIF4B',
 'ADAMTS10',
 'DOCK8',
 'ZZEF1',
 'ARHGAP21',
 'KIAA2018',
 'LRRK1',
 'KIAA1731',
 'KIF4A',
 'LOC101060787',
 'ZNF761',
 'ZNF595',
 'SLC7A14',
 'CLASP1',
 'RBM27',
 'ANO4',
 'PCDHA13',
 'DSG3',
 'AQPEP',
 'TARSL2',
 'ADAMTS14',
 'AP3B1',
 'LPIN2',
 'ANKRD36',
 'KIAA2022',
 'ADAMTSL4',
 'ADAMTS19',
 'ZNF462',
 'FAM214A',
 'DIRC2',
 'PIK3C2B',
 'FMNL1',
 'SLC4A10',
 'PPP1R12B',
 'SLC4A4',
 'PPIP5K2',
 'FNDC3B',
 'MOCS1',
 'MLLT4',
 'DNHD1',
 'AMOT',
 'F5',
 'AMER1',
 'AMBRA1',
 'MMEL1',
 'SERPINB11',
 'PPFIA3',
 'PHF8',
 'PIK3C2G',
 'MMP16',
 'COG2',
 'DICER1',
 'ALS2CR11',
 'C2orf16',
 'KIF2C',
 'SH3TC1',
 'TTI1',
 'KIF3B',
 'ALG13',
 'NLRP6',
 'ENAH',
 'CTNND1',
 'RAB11FIP1',
 'ABCA1',
 'FOXRED2',
 'TTC21A',
 'CTNNA2',
 'PLEKHA5',
 'MTMR11',
 'C3orf20',
 'MS4A14',
 'C1orf94',
 'MON2',
 'QSER1',
 'PPAP2B',
 'SPTB',
 'TAB3',
 'PIK3R1',
 'C1orf116',
 'ALOX5',
 'NRXN3',
 'DZIP3',
 'POTEE',
 'CUL9',
 'PIK3R3',
 'HRC',
 'FOCAD',
 'KIF23',
 'COG4',
 'NLRP8',
 'UBR3',
 'CEP152',
 'PCDHGB1',
 'SOS2',
 'ANKRD30BL',
 'MEGF8',
 'SDHA',
 'DACT1',
 'UTP14A',
 'ANKRD20A5P',
 'BRCA1',
 'BRCA2',
 'BRD4',
 'PIEZO1',
 'SIGLEC10',
 'SP100',
 'PIEZO2',
 'SIGLEC1',
 'USP6',
 'ELL',
 'NLRX1',
 'NLRP9',
 'PCDHGA5',
 'ANKRD31',
 'EZH1',
 'SYDE1',
 'PGAP1',
 'VSIG1',
 'CFHR5',
 'BCL9',
 'DNAI2',
 'FGA',
 'SLC6A8',
 'CFH',
 'GPATCH8',
 'KIAA0232',
 'SDK1',
 'KIAA0430',
 'VMP1',
 'SON',
 'VIT',
 'PTCHD2',
 'PABPC5',
 'VCPIP1',
 'DAPK3',
 'PDS5A',
 'KIAA1210',
 'FHOD1',
 'MLLT3',
 'DUS3L',
 'ENSG00000205233',
 'IFNGR1',
 'MGRN1',
 'PIGO',
 'KIAA1551',
 'MICA',
 'ZNF358',
 'ZNF365',
 'CEP128',
 'MICALL2',
 'IFI16',
 'ANAPC2',
 'SPEF2',
 'PTGER4',
 'MIR600HG',
 'RPH3A',
 'CYFIP1',
 'PLD1',
 'PPP1R3A',
 'EHD1',
 'IFT172',
 'SZT2',
 'UPF1',
 'IGSF22',
 'SYCP2',
 'OTOGL',
 'DUSP10',
 'ELMO1',
 'USP31',
 'GPR111',
 'USP24',
 'ESPN',
 'KIAA1407',
 'RNPC3',
 'SHROOM4',
 'CEP250',
 'ANKFY1',
 ...]

In [57]:
csv.writer?

In [58]:
of2 = '/projects/trans_scratch/validations/workspace/szong/Cervical/variant_bwamem/124_patients/tcga_genes_mutated_in_3_or_mroe_patients.txt'
with open(of2, "w") as output:
    writer = csv.writer(output, lineterminator='\n')
    for val in dfc:
        writer.writerow([val])